### ISSUE TITLE
Cannot use User relationship when skipUserManagement is true

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#10425]
##### **Overview of the issue**

When I skip the user management when generating my JHipster app, I cannot use entities that have relationship with JHipster User entity.

##### **Motivation for or Use Case**

I would like to be able to have relationship with User entity and my entities even if I don't want any user management genration.

##### **Reproduce the error**

```bash
cd /dev/shm/
rm -rf myproject
mkdir myproject
cd myproject
mkdir /dev/shm/m2cache /dev/shm/yarncache
sudo tee myproject.jdl <<EOF
application {
    config {
        baseName MyProject
        cacheProvider no
        clientPackageManager yarn
        jhiPrefix mp
        enableHibernateCache false
        enableTranslation false
        languages [fr]
        nativeLanguage fr
        packageName com.mycompany.myproject
        prodDatabaseType postgresql
        skipUserManagement true
    }
    entities *
}

entity MyEntity {
    myField String
}
relationship OneToOne {
    MyEntity{user} to User
}
EOF
JHIPSTER_VERSION=v6.3.0
sudo chown -R 1000:1000 . /dev/shm/m2cache /dev/shm/yarncache
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v /dev/shm/m2cache:/home/jhipster/.m2 -v /dev/shm/yarncache:/home/jhipster/.cache/yarn -v "$HOME/.gitconfig:/home/jhipster/.gitconfig:ro" jhipster/jhipster:$JHIPSTER_VERSION jhipster import-jdl ./myproject.jdl --force

docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v /dev/shm/m2cache:/home/jhipster/.m2 -v /dev/shm/yarncache:/home/jhipster/.cache/yarn jhipster/jhipster:$JHIPSTER_VERSION ./mvnw
```

The error when running the last line will be:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project my-project: Compilation failure: Compilation failure: 
[ERROR] /home/jhipster/app/src/main/java/com/mycompany/myproject/domain/User.java:[35,32] cannot find symbol
[ERROR]   symbol:   variable LOGIN_REGEX
[ERROR]   location: class com.mycompany.myproject.config.Constants
[ERROR] /home/jhipster/app/src/main/java/com/mycompany/myproject/web/rest/UserResource.java:[169,45] cannot find symbol
[ERROR]   symbol:   variable LOGIN_REGEX
[ERROR]   location: class com.mycompany.myproject.config.Constants
[ERROR] /home/jhipster/app/src/main/java/com/mycompany/myproject/web/rest/UserResource.java:[183,48] cannot find symbol
[ERROR]   symbol:   variable LOGIN_REGEX
[ERROR]   location: class com.mycompany.myproject.config.Constants
[ERROR] /home/jhipster/app/src/main/java/com/mycompany/myproject/service/dto/UserDTO.java:[24,32] cannot find symbol
[ERROR]   symbol:   variable LOGIN_REGEX
[ERROR]   location: class com.mycompany.myproject.config.Constants
```

I tested with JHipster 6.2.0 and it is also happening.

##### **JHipster Version(s)**

```
my-project@0.0.1-SNAPSHOT /home/jhipster/app
`-- generator-jhipster@6.3.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "mp",
    "languages": ["fr"],
    "messageBroker": false,
    "nativeLanguage": "fr",
    "packageName": "com.mycompany.myproject",
    "packageFolder": "com/mycompany/myproject",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "MyProject",
    "cacheProvider": "no",
    "clientPackageManager": "yarn",
    "skipUserManagement": true,
    "jhipsterVersion": "6.3.0",
    "buildTool": "maven",
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "serverPort": "8080",
    "useSass": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["MyEntity"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity MyEntity {
  myField String
}
relationship OneToOne {
  MyEntity{user} to User
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

git version 2.17.1

node: v10.16.3

npm: 6.11.3

yeoman: 3.1.0

yarn: 1.17.3

##### **Browsers and Operating System**

Firefox on Ubuntu 18.04

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Have a look at our documentation at https://www.jhipster.tech/creating-an-app/

> --skip-user-management - Skip the user management generation, both on the back-end and on the front-end (Default: false)

So the behavior here is normal. You can't have a relationship with user, if you decided to skip it at generation.

But what you want is to generate the user management in backend but not in frontend right ?
It is not an option we can support, as it will increase a lot of additional configuration.

**Comment by mraible** [comment]
I would recommend generating your app with user management enabled, then simply delete the user-related UI files (+ tests), routes, and menu items. Should only take a few minutes.

**Comment by murdos** [comment]
I think it's related to https://github.com/jhipster/jhipster-core/pull/278 : I fixed something in jdl-core, but it was not enough.
Since I had to do things differently for work, I never had the need again, and thus never investigate more.

**Comment by pascalgrimaud** [comment]
Ok, so we're not consistent here:
- in generator-jhipster
- in documentation

The problem will be for user who will use skip user management to avoid creating table user, will still have the table, right ?

**Comment by murdos** [comment]
> The problem will be for user who will use skip user management to avoid creating table user, will still have the table, right ?

Not exactly, sorry if I was not really clear: I may have read the report a bit too quickly.
The table is not created, so the error reported here is indeed expected: you can't have relationships if the User entity does not exist (and it does not when user management is skipped).

NB: What I tried to achieve in the past was to have `skipUserManagement=true` and declare an entity named `User` (but with a different content from the JHipster one), but that's something different.

**Comment by pascalgrimaud** [comment]
Yes, I think it is something different.
So @anthony-o, you can follow Matt's advice, it will be quicker and simpler than implementing a new option for skipping user management only on front side and not on backend side.

Closing this as it won't be implemented
