### ISSUE TITLE
`mvn clean -Pprod` makes gulp to fail

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1146]
`mvn clean package -Pprod` deletes the node_modules directory causing gulp to fail.

With grunt, this does not happen because it triggers an `npm install` and `bower install`.

**Comment by gmarziou** [comment]
This is a problem of execution order between yeoman-maven-plugin that runs the npm and bower install and the exec-maven-plugin that runs gulp and is executed first.
In the case of grunt, there's no such issue because grunt is run by yeoman-maven-plugin.

**Comment by gmarziou** [comment]
OK, this seems to be a known issue with a [pending PR for yeoman-maven-plugin](https://github.com/trecloux/yeoman-maven-plugin/pull/10) that seems to be lost in limbo.

**Comment by gmarziou** [comment]
yeoman-maven-plugin has 2 PRs waiting for last 6 months, it seems that @trecloux has lost interest in evolving his project, would you consider switching to another plugin or forking this one as jhipster-maven-plugin?

**Comment by trecloux** [comment]
Wait a bit, I will have a look soon, keeping you updated.

**Comment by gmarziou** [comment]
Great, thanks

**Comment by trecloux** [comment]
The pull request was manually merged on master, could you please test it ?

**Comment by gmarziou** [comment]
Thanks. I tested 0.3 with grunt sucessfully either with old params and new ones.

Unfortunately, it fails for gulp, it seems it does not take into account my configuration or maybe I did it wrong. You can see my test project at https://github.com/gmarziou/jhipster-gulp

When I run `mvn package -Pprod` it runs  fine npm, bower and yo then it fails because it tries to run grunt instead of gulp.

[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.3:build (run-build-tool) on project jhipster: Error during : grunt test --no-color: Process exited with an error: 99 (Exit value: 99) -> [Help 1]

**Comment by trecloux** [comment]
With latest snapshot it looks OK : https://github.com/trecloux/jhipster-gulp/commit/3da96b1e65f6bdfdef688e50c03444509d76ce70
If OK for you too, I can release it

**Comment by gmarziou** [comment]
Yes it works fine! Great work.
Go release it, your version number will go closer to 1.0 :laughing: 
Merci Thomas

**Comment by trecloux** [comment]
I released V0.4, will sync to central soon.

**Comment by vancourse** [comment]
I just downloaded the latest jhipster.. I am still seeing the same issue.. Any ideas?
[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.3:build (run-build-tool) on project jhipster: Error during : grunt test --no-color: Process exited with an error: 99 (Exit value: 99) -> [Help 1]

**Comment by gmarziou** [comment]
No idea, please provide full log and not onlt few lines. Please provide also details on your environment: OS, node version

**Comment by jdubois** [comment]
@gmarziou don't comment on closed tickets...

**Comment by gmarziou** [comment]
Sorry

**Comment by jdubois** [comment]
@gmarziou no problem :-)
It's just that we shouldn't waste time on closed tickets...

**Comment by jdubois** [comment]
@vancourse no offense, but if you have an issue please follow the guidelines and open a new ticket

**Comment by vancourse** [comment]
Sorry, did not know the protocol. Will read up the guidelines and open a new ticket.

**Comment by jdubois** [comment]
Thanks !
