### ISSUE TITLE
Integration tests failing on self reference relationship with filter

### ISSUE THREAD

**Issue by egvimo** [jhipster/generator-jhipster#13687]
##### **Overview of the issue**

If a relationship is declared with a self reference and the filter, the integration test failing.

Exception:

```text
AbcResourceIT > getAllAbcsByParentIsEqualToSomething() FAILED
    javax.persistence.PersistenceException at AbcResourceIT.java:262
        Caused by: org.hibernate.exception.ConstraintViolationException at AbcResourceIT.java:262
```

##### **Reproduce the error**

Run integration tests with the explained configuration.

##### **JHipster Version(s)**

generator-jhipster@7.0.0-beta.1

(Version 6.10.5 has the same problem with a slightly different relationship definition)

##### **JHipster configuration**

The full example can be found in [my repository](https://github.com/egvimo/jhipster-sample-app/tree/13687).

This is the command which I used to create and test the app:

```shell
jhipster import-jdl app.jdl --skip-git --with-entities --force && ./gradlew build
```

The JDL to reproduce:

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
    config {
        baseName sample
        packageName sample
        applicationType monolith
        authenticationType oauth2
        buildTool gradle
        clientFramework angularX
        prodDatabaseType postgresql
        devDatabaseType postgresql
    }
    entities *
}
entity Abc {
    name String unique required
}
relationship ManyToOne {
    Abc{parent} to Abc{children}
}
filter *
  </pre>
  </details>

##### **Browsers and Operating System**

Tried with Windows, Linux and Docker.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by egvimo** [comment]
I still have this issue.

**Comment by VergilSkye** [comment]
this is an edge case when it’s used **_unique required_** fields and **_self reference_** with **_filter_**

When the field is required, generate a static final constant for this field,
when has a self reference and has a filter, generate a function call  _getAllAbcsByParentIsEqualToSomething_()
This function tries to create **2** entities with the same unique required field.
for example: 
```
void getAllAbcsByParentIsEqualToSomething() throws Exception {

        abcRepository.saveAndFlush(abc);
        Abc parent = AbcResourceIT.createEntity(em);
        em.persist(parent);
        
        // omit
    }
```

The first line tries to create abc with a required unique name using the constant DEFAULT_NAME,
and then tries to create a parent with the same name.


**solution**: when creating constants should be taken into consideration if it is unique.


maybe this is too much of an extreme case to be added? Because if you don't use just one of this option nothing breaks

**Comment by egvimo** [comment]
I still have this issue. Is it planned to fix this or is it too much of an edge case?

**Comment by egvimo** [comment]
I have another use case with the same issue, a many to many relationship with additional columns. But the failing tests are the same.

For now I have the following workaround:

```java
void getAllAbcsByParentIsEqualToSomething() throws Exception {
    abcRepository.saveAndFlush(abc);
    Abc parent = AbcResourceIT.createEntity(em);
    parent.setName(parent.getName() + LocalTime.now()); // <- Workaround
    em.persist(parent);
    // ...
}
```

Maybe it would be possible to always generate a unique value for unique fields inside this test?

**Comment by egvimo** [comment]
Keep the issue open, please. 🙂

**Comment by egvimo** [comment]
Keep the issue open, please. 🙂

**Comment by egvimo** [comment]
Keep it open please. I try to come up with a solution.

**Comment by CGarces** [comment]
Can you please check if #15466 solve your issue?

**Comment by egvimo** [comment]
Fixed in 7.2.0 with 868d2873e3611621558d6c602cc3f451d5c16a0d.

**Comment by M4jor-Tom** [comment]
I still have that problem with a 7.4.1 react app with an entity with a bidirectional self OneToOne relationship, I fixed it using JsonIgnore annotations instead of generated JsonIgnoreProperties which seemed perfectly suitable for that jdl, excepted it's not because of [that issue from FasterXML/Jackson-databind](https://github.com/FasterXML/jackson-databind/issues/405). Should that get fixed or remain to each programmer's own implementaiton ?
