### ISSUE TITLE
gulp proxy does not work with websockets

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1639]
First time, I use gulp and websockets and I got this error in Firefox console:

~~~~
GET http://localhost:9000/websocket/tracker/726/qt_z_ydt/websocket [0ms]
00:28:39.417 Firefox can't establish a connection to the server at ws://localhost:9000/websocket/tracker/726/qt_z_ydt/websocket.1 sockjs.js:1213:0
~~~~

So it would seem that gulp proxy cannot proxy ws protocol or maybe there is something to configure, I did not dig further.

**Comment by deepu105** [comment]
could these be related?
https://github.com/jhipster/generator-jhipster/issues/1555

**Comment by gmarziou** [comment]
For PR#1508, I added /websocket/tracker to the URL to be proxied by gulp but this worked only for http not ws. 
Since BrowserSync feature was added, our grunt file is different with regards to proxying, so maybe there's something to dig.

**Comment by deepu105** [comment]
@gmarziou did you check after latest release?

**Comment by deepu105** [comment]
@gmarziou @jdubois not just gulp proxy, websocket doesnt work for even browser sync in grunt setup

**Comment by gmarziou** [comment]
browser-sync is not a big win for me at least on Windows, sinc it was introduced I cannot just do server-less development I must run mvn spring-boot:run even if I don't use the backend. It also locks files.
I have started to use gulp because it's the default build tool for Ionic framework and frankly I would not switch to gulp in JHipster if gulp was not using brower sync.

**Comment by gmarziou** [comment]
It should be tested again since PR #1847 because it upgraded gulp proxy.

**Comment by jdubois** [comment]
For me this doesn't work with BrowserSync, with Grunt, and I even documented [here](http://jhipster.github.io/using_websockets.html).

Shouldn't we add this to the documentation and close this? If BrowserSync doesn't support WebSockets, we can't do much about this.

**Comment by gmarziou** [comment]
Looks like it has been fixed  in BS 2.8.1

https://github.com/BrowserSync/browser-sync/issues/625
https://github.com/BrowserSync/browser-sync/releases

**Comment by PeterEltgroth** [comment]
Nice find @gmarziou 

Last night I had found https://github.com/BrowserSync/browser-sync/issues/611 which seemed to suggest it had worked with BrowserSync 2.6.0 and 2.7.1. Glad they have fixed it again.

**Comment by jdubois** [comment]
And the issue still exists with Grunt, so if you solve this with Gulp.js that would be a huge advantage for using Gulp.js!! cc @PeterEltgroth @amr
