### ISSUE TITLE
One-to-One relationship with User failing using JDL and MapStruct

### ISSUE THREAD

**Issue by jamalzkhan** [jhipster/generator-jhipster#18347]
##### **Overview of the issue**

When creating an application and having a One-to-One relationship with the User and running

`jhipster import-jdl file.jdl`

An error is thrown and can't proceed with generation of entities

> Error running generator entities: Error: Error parsing file 

> src/main/java/com/mycompany/myapp/service/mapper/UserInfoMapper.java: undefined

> At: 1: package com.mycompany.myapp.service.mapper;
> 2:
> 3:
> 4:
> 5: import com.mycompany.myapp.domain.UserInfo;
> 6: import com.mycompany.myapp.service.dto.UserInfoDTO;
> 7:
> 8: import undefined.domain.User;
> 9: import .service.dto.UserDTO;
> 10:
> 11: import org.mapstruct.*;
> 12:
> 13: /**
> 14:  * Mapper for the entity {@link UserInfo} and its DTO {@link UserInfoDTO}.
> 15:  */
> 16: @Mapper(componentModel = "spring")
> 17: public interface UserInfoMapper extends EntityMapper<UserInfoDTO, UserInfo> {
> 18:     @Mapping(target = "user", source = "user", qualifiedByName="userId")
> 19:     UserInfoDTO toDto(UserInfo s);
> 20:
> 21:
> 22:     @Named("userId")
> 23:     @BeanMapping(ignoreByDefault = true)
> 24:     @Mapping(target = "id", source = "id")
> 25:     UserDTO toDtoUserId(User user);
> 26: }
> 27:

##### **Motivation for or Use Case**

I have a custom user having a one-to-one relationship to "UserInfo" and followed the page:  https://www.jhipster.tech/user-entity/

First time this has happened, and have been using JHipster for years (thanks team for such an awesome framework).

##### **Reproduce the error**

My file:

entity UserInfo {
     phoneNumber String
}

relationship OneToOne {
    UserInfo{user} to User
}

dto * with mapstruct

> WARNING! Error at 'UserInfo' definitions: 'otherEntityRelationshipName' is set with value 'userInfo' at relationship 'user' but no back-reference was found at 'user'

> Error running generator entities: Error: Error parsing file src/main/java/com/mycompany/myapp/service/mapper/UserInfoMapper.java: undefined

##### **Suggest a Fix**

I have a feeling this is to do with :

https://github.com/jhipster/generator-jhipster/commit/caf1758382a02a1fc6bebfa4906ee2dfed7fd38f#diff-9eb87a570371f3c01d09f75b33969d1954befe1c1b6afa9f95a4f10595c08470

##### **JHipster Version(s)**

7.8.1

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jhipster",
    "blueprints": [],
    "buildTool": "gradle",
    "cacheProvider": "ehcache",
    "clientFramework": "no",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1649720200224,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": ["UserInfo"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1649720511000,
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity UserInfo {
  phoneNumber String
}
relationship OneToOne {
  UserInfo{user} to User
}

dto UserInfo with mapstruct
service UserInfo with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment (build 16.0.2+7)
OpenJDK 64-Bit Server VM (build 16.0.2+7, mixed mode)

git version 2.32.0 (Apple Git-132)

node: v17.8.0

npm: 8.5.5

Docker version 20.10.11, build dea9396

docker-compose version 1.29.2, build 5becea4c

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>Entity Config for UserInfo.json /summary>

<pre>
{
  "applications": "*",
  "changelogDate": "20220411234151",
  "dto": "mapstruct",
  "embedded": false,
  "entityTableName": "user_info",
  "fields": [
    {
      "fieldName": "phoneNumber",
      "fieldType": "String"
    }
  ],
  "fluentMethods": true,
  "jpaMetamodelFiltering": false,
  "name": "UserInfo",
  "pagination": "no",
  "readOnly": false,
  "relationships": [
    {
      "otherEntityName": "user",
      "otherEntityRelationshipName": "userInfo",
      "ownerSide": true,
      "relationshipName": "user",
      "relationshipType": "one-to-one"
    }
  ],
  "service": "serviceClass"
}

</pre>
</details>

##### **Browsers and Operating System**

MacOS X Monterey 12.1

Not a browser issue

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by CarlosVallsCiscar** [comment]
Same problem with same relationship and the User entity

**Comment by mshima** [comment]
Duplicated of https://github.com/jhipster/generator-jhipster/issues/18293.
Fixed in main.

**Comment by lluisgenoher** [comment]
I still have the same problem, with a monolithic jhipster applications and mysql. Not using webflux.

**Comment by sgpalit** [comment]
why is this closed? i can not still create mappers if user is in relation.. v7.8.1?

**Comment by DanielFran** [comment]
@sgpalit See comment in #18391 

> Should be fixed in main already. See #18347. If you can reproduce using main please let us know in this issue and we reopen.

This issue was duplicated and this has been fixed on main.
We will release soon a new version

**Comment by kvmarkovich** [comment]
@DanielFran I have the same issue. Looking forward to a new version.
