### ISSUE TITLE
`npm run e2e` doesn't pass for reactive-ms JDL

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18570]
##### **Overview of the issue**

To prepare for my Reactive Java Microservices with JHipster talk at Spring I/O on May 26, I decided to try my [demo script](https://github.com/oktadev/java-microservices-examples/blob/main/reactive-jhipster/demo.adoc) with the latest release.

I made it to the part where you run `npm run e2e`. At that point, it fails on two tests:

- When testing /docs 
- When trying to add a new post 

For Swagger, nothing renders and there's a stack trace in the console. 

<img width="1358" alt="Screen Shot 2022-05-03 at 12 04 49" src="https://user-images.githubusercontent.com/17892/166516947-8c2a44df-31b2-4158-ab05-4db2b5ff6540.png">

For adding a new post, it seems that the Save button is never enabled.

![Post e2e test -- new Post page -- should create an instance of Post (failed)](https://user-images.githubusercontent.com/17892/166517141-9e4b274b-a981-4a52-a505-79a7166e5b85.png)

##### **Motivation for or Use Case**

Everything worked when I wrote the post in January 2021 and when I recorded a screencast of it in May 2021.

##### **Reproduce the error**

Run `jhipster jdl reactive-ms`, start all the Docker containers and apps, run `npm run e2e` from the gateway's directory.

##### **JHipster Version(s)**

7.8.1

##### **Browsers and Operating System**

- macOS Monterey, version 12.3.1, M1 Max
- Chrome 100.0.4896.127 
- Node.js 16

**Comment by mshima** [comment]
I will try to reproduce.

**Comment by mshima** [comment]
The swagger problem is because the endpoint are not ready yet.

**Comment by mraible** [comment]
When I tried it in Chrome, it didn't work.

Do you mean it's not implemented or it's not ready to take requests?

**Comment by mshima** [comment]
Not ready to take requests.
I couldn't reproduce.

**Comment by mshima** [comment]
Just tried using chrome, it works.
Maybe it's because it's taking too long to respond, the timeout is 5s.
Are you using amd64 image on m1?

**Comment by mraible** [comment]
Yes, I am using M1 and Cypress is noticeably slower. I'd expect the app to work though, even if the Cypress test fails.

**Comment by mshima** [comment]
I tried to make swagger loaded urls dynamic but failed.
The urls needs to be loaded and parsed before creating the swagger ui.
We can increase the timeout, but the user experience will be worse IMO.

I suggest to create arm64 images.

**Comment by mraible** [comment]
I created Docker images to test things. When I tried starting everything with `docker-compose up`, it took a long time to start all containers. The gateway app was unreachable.

<img width="611" alt="Screen Shot 2022-05-03 at 20 43 20" src="https://user-images.githubusercontent.com/17892/166617961-b2e28113-45e3-4963-83b5-6611873a471f.png">

I stopped all containers and bumped up the available resources.

<img width="595" alt="Screen Shot 2022-05-03 at 20 46 18" src="https://user-images.githubusercontent.com/17892/166618001-4869688f-03fd-40cb-ac03-087544d48052.png">

Then, I enabled Docker Compose V2.

<img width="761" alt="Screen Shot 2022-05-03 at 20 59 36" src="https://user-images.githubusercontent.com/17892/166618011-a7051e70-281c-49d0-b6ea-926e459d5864.png">

Then, I tried `docker compose up`. This seemed to be much faster. Now when I run `npm run e2e`, all tests pass except for creating a post.

<img width="1442" alt="Screen Shot 2022-05-03 at 21 03 42" src="https://user-images.githubusercontent.com/17892/166618092-2854e071-8415-4407-b347-8caa38a1fc7d.png">

I can try on Intel to make sure it's not an M1 issue.

**Comment by mshima** [comment]
@mraible the linked PR should fix the post error.
I could not reproduce the swagger problem, but it should happen if the gateway takes more than 5s.
The PR adds `java:docker:arm64` script to build arm64 docker image.

**Comment by mraible** [comment]
The linked PR does fix the post error. The `/docs` test still fails with Cypress. I tried loading `http://localhost:8080/admin/docs` in Chrome and it takes 11 seconds. If I build Docker containers for all the apps and run them with `docker compose up`, the gateway isn't reachable, even though it looks like it's up in the logs.

Docker seems to indicate that amd64 images might be slow.

<img width="402" alt="Screen Shot 2022-05-03 at 21 35 25" src="https://user-images.githubusercontent.com/17892/166620018-a19ad930-2963-4033-83c9-362f140c7c67.png">

Time to try Intel!

**Comment by mraible** [comment]
I didn't realize I needed to run `npm run java:docker:arm64` to build M1-compatible images. Trying that now...

**Comment by mraible** [comment]
After creating new images with the above command, I tried `docker compose up` and `npm run e2e`. Still doesn't work.

<img width="1132" alt="Screen Shot 2022-05-03 at 21 46 45" src="https://user-images.githubusercontent.com/17892/166620623-d9e4b963-cdff-4927-a319-2193f49ae95a.png">

**Comment by mraible** [comment]
On Intel, starting the apps with `./gradlew` and running `npm run e2e` works just fine. In fact, the Swagger UI loads in a second or so. I'm not sure why it takes so long on the M1.

**Comment by mraible** [comment]
If I build Docker containers on Intel and start with Docker Compose, the product tests fail when running `npm run e2e`. If I restart the store app with Docker Desktop, it works.

<img width="1442" alt="Screen Shot 2022-05-03 at 22 17 08" src="https://user-images.githubusercontent.com/17892/166622520-204dcb92-2705-4288-89a9-238aeedd90bc.png">

**Comment by mshima** [comment]
> After creating new images with the above command, I tried `docker compose up` and `npm run e2e`. Still doesn't work.

You need to delete the amd64 images to recreate as arm64.

**Comment by mshima** [comment]
All green on m1 here.
I have `Experimental Features -> Use the new Virtualization framework` enabled. It provides worst disk performance, but much better processing performance.

**Comment by mraible** [comment]
I can confirm that deleting the amd64 images and turning on Experimental Features solves the problem for me.

<img width="1840" alt="Screen Shot 2022-05-04 at 08 59 44" src="https://user-images.githubusercontent.com/17892/166709676-c37d70ef-c263-4243-a498-08e0f4379c6a.png">

**Comment by mshima** [comment]
Generating both arm64 and amd64 works for docker repository like we do at jhipster-registry.
But doesn’t for local image.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/90550.

**Comment by DanielFran** [comment]
@mshima approved
