### ISSUE TITLE
Running jhipster command throws Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by EspA** [jhipster/generator-jhipster#19627]
##### **Overview of the issue**

Running jhipster command throws Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

Below the stacktrace:

```
➜ jhipster
INFO! Using bundled JHipster
node:internal/modules/cjs/loader:498
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in /opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:340:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:619:3)
    at resolveExports (node:internal/modules/cjs/loader:492:36)
    at Module._findPath (node:internal/modules/cjs/loader:532:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:941:27)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/generator-jhipster/utils/blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.8.0
```

##### **Reproduce the error**

Run jhipster command

##### **JHipster Version(s)**

```
➜  node --version
v18.8.0
➜  npm --version
8.19.1
➜  npm ls -g generator-jhipster
/opt/homebrew/lib
└── generator-jhipster@7.9.3
```

##### **Browsers and Operating System**

MacOS Monterey
Version 12.5.1

**Comment by d-donev** [comment]
I think that only the new version of j-hipster require the namespace to be exported in the package.json

**Comment by chenrui333** [comment]
Why closing this issue? I think it is a real issue.

**Comment by BitFlipp3r** [comment]
I can confirm. Happend to me when upgrading from JHipster 7.8.1 to 7.9.3.
But the fix from @EspA works. Thanks for posting!

**Comment by Akash-Sareen** [comment]
Thanks for the workaround fix from @EspA. It started working for me as well.

**Comment by mshima** [comment]
Installing from v7 git branch should work:
```
npm install -g jhipster/generator-jhipster#v7.x_maintenance
```

**Comment by caocuong2404** [comment]
switch to node v16. JHipster v7.9.3 is working well
![image](https://user-images.githubusercontent.com/50004497/199212864-19d7d19c-493b-45af-9c06-47192f62fff5.png)

**Comment by huynhkimtri** [comment]
Thanks @EspA  for posting the workaround, glad it's helping people.

**Comment by mraible** [comment]
I was trying to reproduce [this issue](https://stackoverflow.com/questions/74440550/new-jhipster-project-all-integration-tests-fail/74451931) that doesn't happen on Mac with Node.js 16. It does happen on Mac with Node 18.

With Windows 11 and Node 18, I'm able to reproduce this issue with JHipster 7.9.3:

```
C:\Users\mraible>jhipster
INFO! Using bundled JHipster
node:internal/modules/cjs/loader:535
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in C:\Users\mraible\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\mraible\AppData\Roaming\npm\node_modules\generator-jhipster\utils\blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.12.1
```

**Comment by vishal423** [comment]
Today, With node.js `v18.x`, I noticed the same issue in the `svelte` blueprint cli `shipster` failing to recognize the exported `cli` and `utils` sub-paths from `generator-jhipster` ( even though I see those under `exports`). 

>node:internal/modules/cjs/loader:535
      throw e;
      ^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cli/cli/jhipster' is not defined by "exports" in /Users/vishal/oss/shipster/node_modules/generator-jhipster/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at requireCLI (/Users/vishal/oss/shipster/cli/shipster.js:72:2) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
Node.js v18.12.1 

I assume the issue shall applies to other blueprints as well.

Everything seems to work fine with node.js `v16.x`

**Comment by kharmaodo** [comment]
I just add this entry "./lib/util/namespace": "./lib/util/namespace.js" as related in the discussion in 
 "exports": {
    ".": "./lib/environment.js",
    "./cli/": "./cli/",
    "./lib/": "./lib/",
    "./lib/util/": "./lib/util/",
    "./adapter": "./lib/adapter.js",
    "./conflicter": "./lib/util/conflicter.js",
    "./log": "./lib/util/log.js",
    "./transform": "./lib/util/transform.js",
    "./package.json": "./package.json",
    **"./lib/util/namespace": "./lib/util/namespace.js"**

**Comment by bhagujava** [comment]
Thanks @kharmaodo  its working fine

**Comment by richwxd** [comment]
Hi,

Please add this line to phrase exports in jhipster/node_modules/yeoman-environment/package.json.
"exports": {
   ...**_,_**
  **_"./lib/util/namespace": "./lib/util/namespace.js"_**
}

**Comment by erikyuzwa** [comment]
This issue hit me today and from what I can gather, it's coming down to `yeoman-environment`. It needs to be version bumped to the latest (as of now `3.13.0`).

I cloned this project to attempt that, and it's already being resolved to the correct version, yet when I run the latest generator to create a project, `yeoman-environment` is still resolving to `3.10.0` so I'm not sure how to push up a PR

**Comment by djassie** [comment]
```bash
sudo vim sudo vim /usr/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json

// this can be /usr/lib or /lib according to the error generated
```
Add 
```json
/"./lib/util/namespace": "./lib/util/namespace.js"
```

**Comment by wlargou** [comment]
Thanks @djassie worked like a charm on macOS Ventura M1 using Node v18.12.1.

**Comment by jrixon** [comment]
Same problem on Ubuntu 22.04.1 LTS and Node.js 19.3.0.

**Comment by mh-masdar** [comment]
> I could fix the problem by adding the export of **"./lib/util/namespace": "./lib/util/namespace.js"** in /opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json


Thanks @EspA for sharing, you saved my day

**Comment by shospodarets** [comment]
Starting 10 of October 2022 Node.js version 18 is LTS, and majority already updated (same as myself 🙂),
and they face this error and broken user experience (on both Windows and Mac), especially the starters.
Since it's fixed in [7.4 milestone](https://github.com/jhipster/generator-jhipster/milestone/210 ) and it looks like relatively manageable amount of changes there, @mshima @DanielFran @mraible WDYT to publish the 7.9.4 version?

**Comment by karimomaya** [comment]
I fixed the problem by adding the export of **"./lib/util/namespace": "./lib/util/namespace.js"** in **/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json**

  ```
"exports": {
    ...
    "./lib/util/namespace": "./lib/util/namespace.js"
    }
```

**Comment by shuoros** [comment]
Thanks @caocuong2404 that's worked for me.

> switch to node v16. JHipster v7.9.3 is working well

**Comment by rgunczer** [comment]
Works on Ubuntu 22.10 too after adding the below line (as EspA commented)

"./lib/util/namespace": "./lib/util/namespace.js" line 

into

~/.nvm/versions/node/v18.12.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json

**Comment by SandraAhlgrimm** [comment]
> I could fix the problem by adding the export of **"./lib/util/namespace": "./lib/util/namespace.js"** in /opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json
> 
> ```
>   "exports": {
>     ".": "./lib/environment.js",
>     "./cli/": "./cli/",
>     "./lib/": "./lib/",
>     "./lib/util/": "./lib/util/",
>     "./adapter": "./lib/adapter.js",
>     "./conflicter": "./lib/util/conflicter.js",
>     "./log": "./lib/util/log.js",
>     "./transform": "./lib/util/transform.js",
>     "./package.json": "./package.json",
>     "./lib/util/namespace": "./lib/util/namespace.js"
> ```

Thanks! Fixed it for me on Mac, Ventura with jhipster 7.9.3

**Comment by dagboujhatem** [comment]
This issues is fixed in this [pull request](https://github.com/jhipster/generator-jhipster/pull/21736). you just have to wait for the validation of this one.

**Comment by xt0fer** [comment]
yes, Mac Ventura; edited the 
**.../node_modules/generator-jhipster/node_modules/yeoman-environment/package.json** file with adding the same thing

```
"./lib/util/namespace": "./lib/util/namespace.js"
```

**Comment by harqib** [comment]
The issue is fixed with @EspA solution, add **"./lib/util/namespace": "./lib/util/namespace.js"** in _.../node_modules/generator-jhipster/node_modules/yeoman-environment/package.json_ 
jhipster v7.9.3

**Comment by devsparkles** [comment]
By the way, it's still a problem with node 20 (and 18) on windows 11
![Capture d'écran 2023-05-02 071701](https://user-images.githubusercontent.com/26492834/235592900-0b0019b5-ccae-4639-b6c1-5fc1650ffcd7.png)

**Comment by erikyuzwa** [comment]
I haven't seen an issue for it yet, but I would imagine one option is to rework the guts of this CLI to get away from Yeoman. 🤔

**Comment by yhojann-cl** [comment]
I confirm the problem in the following versions:

- NodeJS **v18.12.1**
- NPM **9.6.7**
- generator-jhipster **7.9.3**

```
INFO! Using bundled JHipster
node:internal/modules/cjs/loader:535
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in /usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/utils/blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by OpenTechConsult** [comment]
It works for me as well. Thank you.

**Comment by damir78** [comment]
Fresh installation on archlinux with fresh java17, node20 and npm9.6.7:

INFO! Using bundled JHipster
node:internal/modules/cjs/loader:575
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in /usr/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:261:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:591:9)
    at resolveExports (node:internal/modules/cjs/loader:569:36)
    at Module._findPath (node:internal/modules/cjs/loader:643:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1056:27)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster/utils/blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.2.0

**Comment by deepu105** [comment]
closing as release v7.9.4 is being done

**Comment by lehaiha2102** [comment]
> I could fix the problem by adding the export of **"./lib/util/namespace": "./lib/util/namespace.js"** in /opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json
> 
> ```
>   "exports": {
>     ".": "./lib/environment.js",
>     "./cli/": "./cli/",
>     "./lib/": "./lib/",
>     "./lib/util/": "./lib/util/",
>     "./adapter": "./lib/adapter.js",
>     "./conflicter": "./lib/util/conflicter.js",
>     "./log": "./lib/util/log.js",
>     "./transform": "./lib/util/transform.js",
>     "./package.json": "./package.json",
>     "./lib/util/namespace": "./lib/util/namespace.js"
> ```



> Tôi có thể khắc phục sự cố bằng cách thêm xuất **"./lib/util/namespace": "./lib/util/namespace.js"** trong /opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-environment /gói.json
> 
> ```
>   "exports": {
>     ".": "./lib/environment.js",
>     "./cli/": "./cli/",
>     "./lib/": "./lib/",
>     "./lib/util/": "./lib/util/",
>     "./adapter": "./lib/adapter.js",
>     "./conflicter": "./lib/util/conflicter.js",
>     "./log": "./lib/util/log.js",
>     "./transform": "./lib/util/transform.js",
>     "./package.json": "./package.json",
>     "./lib/util/namespace": "./lib/util/namespace.js"
> ```

There is a problem that in /lib folder /util/namespace.js does not exist, can anyone tell me how I can fix this?
