### ISSUE TITLE
Access is denied on windows 11

### ISSUE THREAD

**Issue by UdhayaSoftsuave** [jhipster/generator-jhipster#21810]
Error executing './npmw install', execute it yourself. (Command failed with exit code 1: ./npmw install)

**Comment by mraible** [comment]
I just tried creating a new project using the `main` branch, and I was able to reproduce this issue on Windows 11 (in Parallels). I believe the problem is that it's not running `npmw install` on Windows. I'll add a bug bounty to get this fixed sooner than later. 

<img width="932" alt="Screenshot 2023-04-17 at 11 48 13 AM" src="https://user-images.githubusercontent.com/17892/232568361-eb7c6f8b-19eb-4894-a014-bc56a465de40.png">

**Comment by zhyd1997** [comment]
Seems that it is fixed now?

<img width="1552" alt="Screenshot 2023-04-20 at 19 49 32" src="https://user-images.githubusercontent.com/31362988/233357305-2ccb3c63-bc2f-43ef-8d7d-93763cc41034.png">

**Comment by mraible** [comment]
I tried it with the latest code from the `main` branch and it still happens for me. 

<img width="925" alt="Screenshot 2023-04-20 at 8 44 09 AM" src="https://user-images.githubusercontent.com/17892/233402217-c956f539-c165-4ac3-94c6-8ef7778c2612.png">
