### ISSUE TITLE
Deprecations during both Generation and Building of the application: 8.0.0-beta.2

### ISSUE THREAD

**Issue by anothergoodguy** [jhipster/generator-jhipster#22950]
Hi Team,

There are some warnings on the application both at the time of generation of application and building the generated application.

```
1. During Generation: 

	1. Looks like there are still references to the deprecated Faker references in the file: `prepare-field.mjs`. Details below
		1.1  faker.name is deprecated and recommended to use faker.person for firstName, lastName & jobTitle at line numbers: 54, 56 & 58
		1.2  faker.random.words is deprecated and recommended to use faker.lorem.words at line number 92
		
2. During Build:
	There are a lot of references to the deprecated libs and jars that are not referenced in the actual class and can be safely removed.
	2.1 EntitySearchRepository -> import static org.springframework.data.elasticsearch.client.elc.QueryBuilders.queryStringQuery;
	2.2 EntityService.java -> import static org.springframework.data.elasticsearch.client.elc.QueryBuilders.*;
	2.3 EntityResource -> import static org.springframework.data.elasticsearch.client.elc.QueryBuilders.*;
```
I have tried to make the needed changes on my local setups in both generator file and the generated application; everything works fine. As I am not an active developer, sharing the feedbacks here.

Note: I could not follow the issue template as I could not fit these observations in the same, but not to disobey the process. I can file another issue if you advise 

Thanks in advance!!

**Comment by DanielFran** [comment]
For faker, it has been solved by https://github.com/jhipster/generator-jhipster/pull/22948

**Comment by DanielFran** [comment]
Regarding the 2nd case, can you contribute with a PR? Thanks

**Comment by anothergoodguy** [comment]
will try @DanielFran, still not able to setup a local env successfully; so playing with dockerized jhipster.
Let me give a try

**Comment by qmonmert** [comment]
@DanielFran can we close this ticket?

**Comment by qmonmert** [comment]
@DanielFran can we close this ticket?

**Comment by qmonmert** [comment]
@DanielFran https://opencollective.com/generator-jhipster/expenses/156082 🙂

**Comment by DanielFran** [comment]
@qmonmert approved

**Comment by qmonmert** [comment]
thanks @DanielFran
