### ISSUE TITLE
Error generating new application with 2.27.0

### ISSUE THREAD

**Issue by wimdeblauwe** [jhipster/generator-jhipster#2669]
I am trying to generate a new application. At the end, the following output is shown:

```
messageformat#0.1.8 src/main/webapp/bower_components/messageformat

angular-translate#2.8.1 src/main/webapp/bower_components/angular-translate
└── angular#1.4.8

angular-local-storage#0.2.3 src/main/webapp/bower_components/angular-local-storage

jquery#2.1.4 src/main/webapp/bower_components/jquery
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
    at onErrorNT (internal/child_process.js:345:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
```

**Comment by pascalgrimaud** [comment]
Can you show your .yo-rc.json file plz ?

**Comment by pascalgrimaud** [comment]
Please follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines) about submitting an issue and provide some details.

**Comment by wimdeblauwe** [comment]
The file contents is this:

```
{
  "generator-jhipster": {
    "baseName": "myapp",
    "packageName": "com.company.myapp",
    "packageFolder": "com/company/myapp",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": true,
    "rememberMeKey": "2007bea76babde242e7f6bcc2c55841bb62a8c79",
    "testFrameworks": [
      "protractor"
    ]
  }
}
```

**Comment by deepu105** [comment]
This definitely seems like environment issue and not a JHipster issue.

Few suggestions

Delete your bower_components folder
Delete your node_modules folder
Now run npm install and wait for it to complete
Run npm install -g bower
Run bower install

If still there is issue try to un install node and npm then install a
stable LTS version and try above steps again

**Comment by pascalgrimaud** [comment]
Like Deepu said :
> This definitely seems like environment issue and not a JHipster issue.

I used your .yo-rc.json and no problem for generating a JHipster application

**Comment by wimdeblauwe** [comment]
I tried the same but with "grunt" instead of "gulp", but still the same issue. I already followed the steps to reinstall node found here: https://raibledesigns.com/rd/entry/getting_started_with_jhipster_on

But still the same issue. This is with grunt:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn grunt ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```

**Comment by jdubois** [comment]
Try a `npm install` this should solve the issue

**Comment by sayedasadali** [comment]
hey @wimdeblauwe , I ran into the same issue. turns out I had to reinstall `gulp` and run `gulp install` to make things right

**Comment by roundwheel** [comment]
On a Mac, after reinstalling JHipster and dependencies following the "Local installation with Yarn" steps here https://jhipster.github.io/installation/, I was still getting this error.  Running the command listed in the note under step 9:

export PATH="$PATH:`yarn global bin`:$HOME/.config/yarn/global/node_modules/.bin"

... resolved the issue.
