### ISSUE TITLE
"max key length is 767 bytes" with MySQL/OAuth2

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#307]
I'm using MySQL in "prod" mode, and I have the following error at start up time (by Liquibase):

"Specified key was too long; max key length is 767 bytes"

This is caused by this issue: http://wildlyinaccurate.com/mysql-specified-key-was-too-long-max-key-length-is-767-bytes

And the "oauth_client_details" table has a clientId PK which causes the issue:
 <column name="client_id" type="VARCHAR(256)">
                <constraints nullable="false" primaryKey="true"/>
            </column>

-> could this field be smaller?

**Comment by c0nscience** [comment]
Hi, I know that issue was closed a long time ago, but I just want to say that I still got this error with v2.
Created a new project with the yeoman generator, set the dev db to 'mysql', get the above mentioned error with a fresh created utf-8 mysql schema. I changed all 'varchar(256)' to 'varchar(255)' as @fyelci mentioned earlier to fix the error.

**Comment by LuisHu** [comment]
I changed all 'varchar(256)' to 'varchar(255)' as above mentioned earlier, this error is fixed.

**Comment by gruenewald** [comment]
Hi, i still have the error with mysql + utf-8 schema + OAuth 2.0. I Use jhipster version 2.7.0.

**Comment by piedrahitac** [comment]
I can also confirm this issue is still present in JHipster 2.7.0.

And I can also confirm that the aforementioned solution fixed the problem.

**Comment by jdubois** [comment]
If the issue is still here I'm reopening this

**Comment by yarix** [comment]
same problem and solution here too (mySql 5.6.23, win64, default collation: utf-8_general_ci)
thanks for reopening.
