### ISSUE TITLE
unable to import-jdl for gateways with no sql

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#5191]
##### **Overview of the issue**

Since 4.0.3 it's able to generate UAA based gateways without database. It's still needed to add microservice entities using JDL. But this fails, as import-jdl assumes a app must have a database.

The error message is

```
The jdl is being parsed.
{ name: 'IllegalArgumentException',
  message: 'The passed database type must either be \'sql\', \'mysql\', \'mariadb\', \'postgresql\', \'oracle\', \'mssql\', \'mongodb\', or \'cassandra\'',
  prototype: 
   Error
       at new buildException (/home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/jhipster-core/lib/exceptions/exception_factory.js:43:25)
       at Object.getIsType (/home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/jhipster-core/lib/core/jhipster/field_types.js:148:11)
       at init (/home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/jhipster-core/lib/parser/jdl_parser.js:49:23)
       at Object.parse [as convertToJDL] (/home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/jhipster-core/lib/parser/jdl_parser.js:38:3)
       at constructor.parseJDL (/home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/generator-jhipster/generators/import-jdl/index.js:49:41)
       at Object.<anonymous> (/home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/yeoman-generator/lib/base.js:439:23)
       at /home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
       at /home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
       at /home/david/Projekte/microXchng/code/uaa-setup/gw403/node_modules/yeoman-generator/lib/base.js:440:9
       at runCallback (timers.js:649:20) }
```

##### **Motivation for or Use Case**

Need to generate frontend client for entities

##### **Reproduce the error**

Try to import a JDL file using `yo jhipster:import-jdl`

##### **Related issues**

allow uaa gateways to have no database configured

##### **Suggest a Fix**

I'm sure this has to be done on jhipster/jhipster-core. 
In particular we should assert the situation, that for gateways (with uaa) **all** entities must be mapped to a microservice. 
##### **JHipster Version(s)**

4.0.3

##### **JHipster configuration**

UAA gateway with no Database configured

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The problem is that the gateway validates JDL entities against its own database, rather than the microservice database.  https://github.com/jhipster/jhipster-core/issues/60

Maybe we shouldn't validate microservice entities when generating for a gateway?  There's no easy way to get the microservice database type

**Comment by xetys** [comment]
this is what I suggest....all "microservice" marked entities should not be validated against databases

**Comment by MathieuAA** [comment]
If the solution is just to simply turn the validation off, then it's easy.

**Comment by MathieuAA** [comment]
I'm opening a ticket in JCore.

**Comment by MathieuAA** [comment]
@xetys @ruddell @jdubois Or... I may have a better approach than just turning things off and on.
Since the very beginning, the dumped JSON is a place to store data. Why not store the microservice DB in this JSON?

**Comment by ruddell** [comment]
I like @xetys's solution - to not validate entities assigned to a microservice when generating in a gateway

@MathieuAA Do you mean adding a field in the JDL for the databaseType of each entity?

**Comment by MathieuAA** [comment]
@ruddell no, only the JSON

**Comment by ruddell** [comment]
@MathieuAA How would you get the database type from the JDL?

I want be able to import the following JDL to a gateway, database validation shouldn't matter because it's mapped to a microservice.  It works when I run `yo jhipster:entity Game`, but I don't want to have to run that for every entity.
```
entity Game {
     name String,
     time ZonedDateTime // fails for Cassandra gateways   
}

microservice Game with sport
```
A workaround is to temporarily change prodDatabaseType in `.yo-rc.json` to mysql (or your choice) and import the JDL.

**Comment by deepu105** [comment]
Another option would be to specify the relative path for the microservice from gateway and then go in and read the db type form its yo-rc file something like
`microservice Game with sport(../sportService)`

**Comment by MathieuAA** [comment]
Too ugly =/ we know where the microservice is, and its name. Wé can fetch the info

Le 14 février 2017 10:26:11 GMT+01:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>Another option would be to specify the relative path for the
>microservice from gateway and then go in and read the db type form its
>yo-rc file something like
>`microservice Game with sport(../sportService)`
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/5191#issuecomment-279653125

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
That's what I'm doing for David's ticket, so it's easy for me

**Comment by deepu105** [comment]
@MathieuAA we actually dont knwo where the microservice is all the time. You are assuming that people will have all the microservice in the same parent folder but in reality we dont enforce that or even the folder name for that case so we cannot always get the path from the microservice name alone.

**Comment by MathieuAA** [comment]
Ah that's too bad =/

Le 14 février 2017 17:42:39 GMT+01:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>@MathieuAA we actually dont knwo where the microservice is all the
>time. You are assuming that people will have all the microservice in
>the same parent folder but in reality we dont enforce that or even the
>folder name for that case so we cannot always get the path from the
>microservice name alone.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/5191#issuecomment-279762391

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
@deepu105 Your solution is the best one. I'll implement it and then add it to the documentation.

**Comment by jdubois** [comment]
The front-end should only use the REST endpoints underneath, and not be tied to a specific database (this is not totally true: we don't have the same pagination option for Cassandra). @MathieuAA I'm not sure which solution you find is the "best", but I would just remove the validation.

**Comment by MathieuAA** [comment]
@jdubois that's one solution, but if we can specify where the microservice is then we don't have to remove anything. I'll let you guys decide which solution is the best, but I'd rather specify where the microservice is in the JDL.

**Comment by jdubois** [comment]
Yes, but as @deepu105 said, we don't know where the microservice will be - people can install it anywhere... So we can't store that information, and so we can't do it.

**Comment by MathieuAA** [comment]
You're right, it could be moved... Let''s just remove the validation.

**Comment by deepu105** [comment]
@MathieuAA did you fix this?

**Comment by pascalgrimaud** [comment]
Ping @MathieuAA :)

**Comment by MathieuAA** [comment]
Oh. I didn't see this message, sorry! Not yet. I've actually forgotten there's still this issue. I'll fix it right now.

**Comment by MathieuAA** [comment]
The PR: #5764

**Comment by xetys** [comment]
I tested today again, with 4.5.2, it still shows the same error message, when using a gateway with no sql...

if i add "microservice X with Y", it then forbids me to use relationship, as "I am using NoSQL", which doesn't support relationships

**Comment by MathieuAA** [comment]
@xetys I'll look into it...

**Comment by MathieuAA** [comment]
@xetys, just to be clear about what I am to do here:
  - You have a gateway, and _n_ microservices,
  - The gateway's DB is of a NoSQL kind,
  - At least of one your microservices is.

For me it's a **different kind of issue** as, when your JDL is parsed, it notices you use relationships when your current application (the gateway) can't.
If I haven't forgotten anything here, I'll fix it right away.

**Comment by MathieuAA** [comment]
@xetys I've pushed something in the JHCore project, but I want to test some cases before proposing a PR.

**Comment by xetys** [comment]
i will check asap

**Comment by xetys** [comment]
There is still an issue with the parseJDL function in the import-jdl generator. The applicationType should be passed, too. After setting that option locally, I could generate the gateway!

**Comment by deepu105** [comment]
@xetys @MathieuAA can we close this? is it still an issue? I see that a PR was merged for this and looks like it should be solved

**Comment by MathieuAA** [comment]
@deepu105 I think it can be closed, yes.
