### ISSUE TITLE
Cannot start UAA server

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#5215]
##### **Overview of the issue**

After the application starts, the first message I see is:

```
2017-02-15 13:30:52.504  WARN 4004 --- [  restartedMain] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/sample/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
```
As I know, 8888 is the default port for config server. But registry, which also acts as a config server, has port 8761. So why does it try to connect to 8888?  
Then I see next messages: 

```
2017-02-15 13:31:13.629 DEBUG 4004 --- [  restartedMain] c.n.d.s.r.aws.ConfigClusterResolver      : Config resolved to [AwsEndpoint{ serviceUrl='http://admin:${jhipster.registry.password}@localhost:8761/eureka/', region='us-east-1', zone='defaultZone'}]
```

```
2017-02-15 13:31:13.942 DEBUG 4004 --- [  restartedMain] n.d.s.t.j.AbstractJerseyEurekaHttpClient : Created client for url: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
2017-02-15 13:31:13.943 DEBUG 4004 --- [  restartedMain] n.d.s.t.j.AbstractJerseyEurekaHttpClient : Jersey HTTP GET http://admin:${jhipster.registry.password}@localhost:8761/eureka//apps/?; statusCode=N/A
2017-02-15 13:31:13.967 ERROR 4004 --- [  restartedMain] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

java.lang.IllegalArgumentException: Illegal character in authority at index 7: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
```
Seems like `jhipster.registry.password` has not been resolved.  
Then I have the following message (but I think it depends on the previous):

```
2017-02-15 13:31:13.981  WARN 4004 --- [  restartedMain] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failure
2017-02-15 13:31:13.984 ERROR 4004 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_SAMPLE/sample:73448f1a96f7ba1b6abba601c82a511c - was unable to refresh its cache! status = Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
```

Or is it a bug, or a generated app should be configured manually. Some mini-guide would be great. Because I read the existed many times and cannot even start new applications.

##### **Reproduce the error**

- Start JHipster registry
- Start generated UAA

##### **JHipster Version(s)**

```
D:\microservices\uaa
`-- generator-jhipster@4.0.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "sample",
    "packageName": "io.delverdev.microservices",
    "packageFolder": "io/delverdev/microservices",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableTranslation": false,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.1.windows.1

node: v6.9.5

npm: 3.10.10

yarn: 0.19.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
This is usually the case when your bootstrap.yml is not read, it can be due to:
- not setting a valid profile
- not setting right directory if run from IDE

**Comment by jdubois** [comment]
Yes you need to check your JHipster Registry URL, for example try to "curl" it with your login/password to see if it works. Have also a look at #5122 I think it's kind of the same issue, and that was solved recently.
Your "jhipster.registry.password" should be set up in your `bootstrap-*.yml` files, have a look if it's there, and if you can use it with a "curl" on the Registry. If it fails, you can also write the full URL (with the real password and not the variable) in your Registry URL, that will make it work -> if you do this, please add a comment, as this would mean something is wrong.

**Comment by delverdev** [comment]
Without variable, the application starts, but I still receive:
```
2017-02-15 20:56:40.439  WARN 5200 --- [  restartedMain] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/sample/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
```
Also the application registers 3 times:

![capture](https://cloud.githubusercontent.com/assets/7104443/22990403/bf5bc126-f3c1-11e6-9d7c-aa255ac57aa6.PNG)

By the way, Docker's `app.yml` has a variable with two dollar signs. I don't know if it's correct or not:
```
- SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
```

**Comment by ruddell** [comment]
@delverdev I was able to build a UAA docker image with your `.yo-rc.json` and it starts up fine.  

The two dollar signs is from the [docker-compose docs](https://docs.docker.com/compose/compose-file/#/variable-substitution): 
> You can use a $$ (double-dollar sign) when your configuration needs a literal dollar sign. This also prevents Compose from interpolating a value, so a $$ allows you to refer to environment variables that you don’t want processed by Compose.

**Comment by jdubois** [comment]
Yes the $$ is correct indeed, even if it's very surprising :-)

**Comment by delverdev** [comment]
@ruddell, can you build it without Docker? Now I will try to regenerate and reproduce it with detailed steps. 
Also I have had the following parts in logs ("Not found or not setup for this application"):

```
log.info("\n----------------------------------------------------------\n\t" +
                "Config Server: \t{}\n----------------------------------------------------------",
            configServerStatus == null ? "Not found or not setup for this application" : configServerStatus);
```

**Comment by delverdev** [comment]
1. Forked 'jhipster-registry'.
2. Cloned it via IDEA.
3. Started via "Run JHipsterRegistry". I can open the web page and login with "admin;admin", but in `Health` tab `discoveryComposite - eureka` is `UNKNOWN`.

```
2017-02-15 22:15:51.393  INFO 1344 --- [  restartedMain] i.g.jhipster.registry.JHipsterRegistry   : The following profiles are active: native,dev
2017-02-15 22:16:00.014  WARN 1344 --- [  restartedMain] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'refreshScope' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2017-02-15 22:16:02.393 DEBUG 1344 --- [  restartedMain] i.g.j.r.config.MetricsConfiguration      : Registering JVM gauges
2017-02-15 22:16:03.468 DEBUG 1344 --- [  restartedMain] i.g.j.r.config.MetricsConfiguration      : Initializing Metrics JMX reporting
2017-02-15 22:16:07.508  INFO 1344 --- [  restartedMain] org.xnio                                 : XNIO version 3.3.6.Final
2017-02-15 22:16:07.725  INFO 1344 --- [  restartedMain] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.6.Final
2017-02-15 22:16:12.033  INFO 1344 --- [  restartedMain] i.g.j.registry.config.WebConfigurer      : Web application configuration, using profiles: [native, dev]
2017-02-15 22:16:12.052 DEBUG 1344 --- [  restartedMain] i.g.j.registry.config.WebConfigurer      : Initializing Metrics registries
2017-02-15 22:16:12.088 DEBUG 1344 --- [  restartedMain] i.g.j.registry.config.WebConfigurer      : Registering Metrics Filter
2017-02-15 22:16:12.089 DEBUG 1344 --- [  restartedMain] i.g.j.registry.config.WebConfigurer      : Registering Metrics Servlet
2017-02-15 22:16:12.143  INFO 1344 --- [  restartedMain] i.g.j.registry.config.WebConfigurer      : Web application fully configured
2017-02-15 22:16:12.672  INFO 1344 --- [  restartedMain] i.g.jhipster.registry.JHipsterRegistry   : Running with Spring profile(s) : [native, dev]
2017-02-15 22:16:18.476  INFO 1344 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Client configured to neither register nor query for data.
2017-02-15 22:16:18.757  INFO 1344 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1487189778757 with initial instances count: 0
2017-02-15 22:16:19.374  INFO 1344 --- [  restartedMain] c.n.eureka.DefaultEurekaServerContext    : Initializing ...
2017-02-15 22:16:19.449  INFO 1344 --- [  restartedMain] c.n.eureka.cluster.PeerEurekaNodes       : Adding new peer nodes [http://localhost:8761/eureka/]
2017-02-15 22:16:20.658  INFO 1344 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2017-02-15 22:16:20.791  INFO 1344 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2017-02-15 22:16:20.876  INFO 1344 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2017-02-15 22:16:20.886  INFO 1344 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2017-02-15 22:16:22.144  INFO 1344 --- [  restartedMain] c.n.eureka.cluster.PeerEurekaNodes       : Replica node URL:  http://localhost:8761/eureka/
2017-02-15 22:16:22.231  INFO 1344 --- [  restartedMain] c.n.e.registry.AbstractInstanceRegistry  : Finished initializing remote region registries. All known remote regions: []
2017-02-15 22:16:22.254  INFO 1344 --- [  restartedMain] c.n.eureka.DefaultEurekaServerContext    : Initialized
2017-02-15 22:16:34.273  WARN 1344 --- [  restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2017-02-15 22:16:34.337  INFO 1344 --- [  restartedMain] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2017-02-15 22:16:34.426  WARN 1344 --- [  restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2017-02-15 22:16:34.433  INFO 1344 --- [  restartedMain] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2017-02-15 22:16:36.536  INFO 1344 --- [      Thread-14] c.n.e.r.PeerAwareInstanceRegistryImpl    : Got 1 instances from neighboring DS node
2017-02-15 22:16:36.761  INFO 1344 --- [      Thread-14] c.n.e.r.PeerAwareInstanceRegistryImpl    : Renew threshold is: 1
2017-02-15 22:16:36.762  INFO 1344 --- [      Thread-14] c.n.e.r.PeerAwareInstanceRegistryImpl    : Changing status to UP
2017-02-15 22:16:36.848  INFO 1344 --- [  restartedMain] i.g.jhipster.registry.JHipsterRegistry   : Started JHipsterRegistry in 55.546 seconds (JVM running for 59.943)
```

4. Created UAA with the old `yorc` configuration (successfully).
5. Imported as a Gradle project.
6. Started via "Run SampleApp". Have errors that I've had before.
7. Replaced all `${jhipster.registry.password}` with `admin`.
8. Started. Now registered 2 times, but with the warn mentioned in my previous comments.

**Comment by pascalgrimaud** [comment]
@delverdev : sometimes I have the same like you, so I put `-Dspring.profiles.active=dev` in VM options of IntelliJ, to force the microservice to take this profile

**Comment by gmarziou** [comment]
Yes this is what I tried to explain 12 hours ago :)
Also your log extract is too late, it does not show the profile used.

**Comment by pascalgrimaud** [comment]
it happens quite often to my collegues, so I think it need to be documented

**Comment by jdubois** [comment]
Oh yes I had that same issue once!

Le 16 févr. 2017 1:14 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

it happens quite often to my collegues, so I think it need to be documented

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5215#issuecomment-280185905>,
or mute the thread

**Comment by jdubois** [comment]
Then we have an issue, the 'dev' profile should be selected by default if
nothing is done.

**Comment by delverdev** [comment]
Thanks, finally it works! But I have something strange in registry's logs after the registry and uaa restart:

```
----------------------------------------------------------
	Application 'jhipster-registry' is running! Access URLs:
	Local: 		http://127.0.0.1:8761
	External: 	http://192.168.1.31:8761
	Profile(s): 	[native, dev]
----------------------------------------------------------
2017-02-16 15:01:18.730  INFO 1016 --- [      Thread-14] c.n.e.r.PeerAwareInstanceRegistryImpl    : Changing status to UP
2017-02-16 15:02:16.994  INFO 1016 --- [ XNIO-2 task-13] c.s.j.s.i.a.WebApplicationImpl           : Initiating Jersey application, version 'Jersey: 1.19.1 03/11/2016 02:08 PM'
2017-02-16 15:02:17.297  INFO 1016 --- [ XNIO-2 task-13] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2017-02-16 15:02:17.356  INFO 1016 --- [ XNIO-2 task-13] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2017-02-16 15:02:17.384  INFO 1016 --- [ XNIO-2 task-13] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2017-02-16 15:02:17.400  INFO 1016 --- [ XNIO-2 task-13] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2017-02-16 15:02:18.927  INFO 1016 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
2017-02-16 15:02:50.913  WARN 1016 --- [  XNIO-2 task-6] c.n.e.registry.AbstractInstanceRegistry  : DS: Registry: lease doesn't exist, registering resource: SAMPLE - sample:fc7afc2781d8f0e152d02c43e1c2de44
2017-02-16 15:02:50.923  WARN 1016 --- [  XNIO-2 task-6] c.n.eureka.resources.InstanceResource    : Not Found (Renew): SAMPLE - sample:fc7afc2781d8f0e152d02c43e1c2de44
2017-02-16 15:02:51.973  INFO 1016 --- [ XNIO-2 task-10] c.n.e.registry.AbstractInstanceRegistry  : Registered instance SAMPLE/sample:fc7afc2781d8f0e152d02c43e1c2de44 with status STARTING (replication=false)
2017-02-16 15:02:54.991 DEBUG 1016 --- [ XNIO-2 task-12] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:02:55.222 ERROR 1016 --- [get_localhost-4] c.n.e.cluster.ReplicationTaskProcessor   : Network level connection to peer localhost; retrying after delay

com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.netflix.eureka.cluster.DynamicGZIPContentEncodingFilter.handle(DynamicGZIPContentEncodingFilter.java:48)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
	at com.netflix.eureka.transport.JerseyReplicationClient.submitBatchUpdates(JerseyReplicationClient.java:116)
	at com.netflix.eureka.cluster.ReplicationTaskProcessor.process(ReplicationTaskProcessor.java:71)
	at com.netflix.eureka.util.batcher.TaskExecutors$BatchWorkerRunnable.run(TaskExecutors.java:187)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:158)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:271)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:232)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
	... 10 common frames omitted

2017-02-16 15:02:55.816 DEBUG 1016 --- [ XNIO-2 task-15] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:02:56.716 DEBUG 1016 --- [  XNIO-2 task-7] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:02:57.049 DEBUG 1016 --- [ XNIO-2 task-11] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:02:57.383 DEBUG 1016 --- [  XNIO-2 task-4] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:02:57.421 ERROR 1016 --- [et_localhost-16] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 401; discarding 1 replication tasks
2017-02-16 15:02:57.561  WARN 1016 --- [et_localhost-16] c.n.eureka.util.batcher.TaskExecutors    : Discarding 1 tasks of TaskBatchingWorker-target_localhost-16 due to permanent error
2017-02-16 15:03:00.355  INFO 1016 --- [  XNIO-2 task-9] c.n.e.registry.AbstractInstanceRegistry  : Registered instance SAMPLE/sample:fc7afc2781d8f0e152d02c43e1c2de44 with status STARTING (replication=false)
2017-02-16 15:03:01.115 DEBUG 1016 --- [ XNIO-2 task-16] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:03:01.158 ERROR 1016 --- [et_localhost-12] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 401; discarding 1 replication tasks
2017-02-16 15:03:02.151  WARN 1016 --- [et_localhost-12] c.n.eureka.util.batcher.TaskExecutors    : Discarding 1 tasks of TaskBatchingWorker-target_localhost-12 due to permanent error
2017-02-16 15:03:04.100  INFO 1016 --- [  XNIO-2 task-3] c.n.e.registry.AbstractInstanceRegistry  : Registered instance SAMPLE/sample:fc7afc2781d8f0e152d02c43e1c2de44 with status UP (replication=false)
2017-02-16 15:03:04.730 DEBUG 1016 --- [  XNIO-2 task-5] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:03:04.798 ERROR 1016 --- [get_localhost-9] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 401; discarding 1 replication tasks
2017-02-16 15:03:04.823  WARN 1016 --- [get_localhost-9] c.n.eureka.util.batcher.TaskExecutors    : Discarding 1 tasks of TaskBatchingWorker-target_localhost-9 due to permanent error
2017-02-16 15:03:18.927  INFO 1016 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
2017-02-16 15:03:23.020 DEBUG 1016 --- [  XNIO-2 task-6] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:03:23.038 ERROR 1016 --- [et_localhost-11] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 401; discarding 1 replication tasks
2017-02-16 15:03:23.056  WARN 1016 --- [et_localhost-11] c.n.eureka.util.batcher.TaskExecutors    : Discarding 1 tasks of TaskBatchingWorker-target_localhost-11 due to permanent error
2017-02-16 15:03:53.103 DEBUG 1016 --- [  XNIO-2 task-4] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:03:53.118 ERROR 1016 --- [et_localhost-11] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 401; discarding 1 replication tasks
2017-02-16 15:03:53.119  WARN 1016 --- [et_localhost-11] c.n.eureka.util.batcher.TaskExecutors    : Discarding 1 tasks of TaskBatchingWorker-target_localhost-11 due to permanent error
2017-02-16 15:04:18.928  INFO 1016 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
2017-02-16 15:04:23.155 DEBUG 1016 --- [  XNIO-2 task-3] i.g.j.r.s.Http401UnauthorizedEntryPoint  : Pre-authenticated entry point called. Rejecting access
2017-02-16 15:04:23.170 ERROR 1016 --- [et_localhost-18] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 401; discarding 1 replication tasks
2017-02-16 15:04:23.180  WARN 1016 --- [et_localhost-18] c.n.eureka.util.batcher.TaskExecutors    : Discarding 1 tasks of TaskBatchingWorker-target_localhost-18 due to permanent error
```
And UAA registers 3 times again.
P.S. in run configuration, there is input "Active Profiles". That allows to set profiles easier (for errors above I tested both options).
