### ISSUE TITLE
Add a maven goal to run "Liquibase Hibernate"

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#754]
(we do it first for Maven, we'll see later to port it to Gradle)

We should have a Maven Goal that runs diffs automatically using "Liquibase Hibernate"
https://github.com/liquibase/liquibase-hibernate/wiki

That way we could have the Liquibase changelog automatically generated when a user modifies an entity.

cc @nvoxland

**Comment by jdubois** [comment]
@nvoxland this NPE is in fact a new issue, as this was working on previous versions.

So I am with Liquibase (3.4.0-SNAPSHOT) , liquibase-maven-plugin (3.4.0-SNAPSHOT) and liquibase-hibernate4.2 (3.5-SNAPSHOT)

The issue is because I have a @CollectionTable mapping (it is [here in our source code](https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/java/package/domain/_PersistentAuditEvent.java#L43)), and when Liquibase-Hibernate4.2 tries to do a PrimaryKeySnapshotGenerator, we have a table without a PK, so the hbnPrimaryKeyName is null -> that causes the exception.

**Comment by jdubois** [comment]
@nvoxland 
We also need to use Liquibase 3.4.0-SNAPSHOT because of this issue, which is also a blocker for us:
https://github.com/liquibase/liquibase/pull/305

**Comment by nvoxland** [comment]
It will probably be a while until I'm ready for 3.4.0 to be released, so 3.3.2 is probably what you should be testing/targeting. I'll bring liquibase/liquibase#305 into the 3.3.x branch for 3.3.2. I'll look at the null pointer issue.

**Comment by nvoxland** [comment]
The null pointer issue should be fixed now in liquibase-hibernate/master

**Comment by nvoxland** [comment]
The fix in liquibase/liquibase#305 is already in the 3.3.x branch. Are you seeing a related problem still with 3.3.2-SNAPSHOT?

**Comment by jdubois** [comment]
@nvoxland in 3.3.2-SNAPSHOT I still have the NPE issue (I guess you didn't backport it yet?), but the https://github.com/liquibase/liquibase/pull/305 is OK
The diffExcludeObjects is also here, but I can't test it because of the NPE

**Comment by jdubois** [comment]
I have opened issue https://github.com/liquibase/liquibase-hibernate/issues/72 about the NPE

**Comment by nvoxland** [comment]
The NPE is fixed up now.

**Comment by jdubois** [comment]
@nvoxland we have everything working!!!! Thanks!
I'm eagerly awaiting your release of liquibase 3.3.2 and Liquibase-hibernate4 3.5 !
