### ISSUE TITLE
Blueprint write phase, ENOENT: no such file or directory

### ISSUE THREAD

**Issue by pasqualevitale** [jhipster/generator-jhipster#7925]
##### **Overview of the issue**

The bug is related to the usage of implemented blueprint, this case is about spring-controller sub-generator, but it seems the same for the others sub-generator.
When you simply implements: 
```
get writing() {
     // Here we are not overriding this phase and hence its being handled by JHipster
     return super._writing();
}
```
during the app generation with this blueprint, in `_writing` is thrown 
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Copying template src/main/java/package/web/rest/Resource.java.ejs failed. [Error: ENOENT: no such file or directory, open 'D:\tests\b-helloworld\generators\spring-controller\templates\src\main\java\package\web\rest\Resource.java.ejs']
    at Environment.error (D:\tests\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:157:40)
    at module.exports.error (D:\tests\jhipster\generator-jhipster\generators\generator-base.js:1981:18)
    at ejs.renderFile (D:\tests\jhipster\generator-jhipster\generators\utils.js:197:23)
    at tryHandleCache (D:\tests\jhipster\generator-jhipster\node_modules\ejs\lib\ejs.js:254:14)
    at Object.exports.renderFile (D:\tests\jhipster\generator-jhipster\node_modules\ejs\lib\ejs.js:482:10)
    at Object.renderContent (D:\tests\jhipster\generator-jhipster\generators\utils.js:193:9)
    at module.exports.template (D:\tests\jhipster\generator-jhipster\generators\generator-base-private.js:636:23)
    at module.exports.writing (D:\tests\jhipster\generator-jhipster\generators\spring-controller\index.js:138:22)
    at Object.<anonymous> (D:\tests\jhipster\generator-jhipster\node_modules\yeoman-generator\lib\index.js:399:25)
    at D:\tests\jhipster\generator-jhipster\node_modules\run-async\index.js:25:25
```
The generator tries to open `D:\tests\b-helloworld\generators\spring-controller\templates\src\main\java\package\web\rest\Resource.java.ejs`
but it should tries to open `D:\tests\jhipster\generator-jhipster\spring-controller\templates\src\main\java\package\web\rest\Resource.java.ejs`

To workaround the problem I have to copy the templates into my blueprint folder templates.

If I use the super._writing I don't expect that I need to copy the "super templates" in my blueprint project.

##### **Motivation for or Use Case**

In debug mode, I notice that the context during the _writing call method doesn't change, it is always on my-blueprint context. (At runtime, the context of `template` method of `generator-base-private.js`)

If I want to around the _writing phase, or simply use the super._writing, I need to copy the templates from sources, in order to fix the problem.
e.g. arounding the _writing phase
```
    get writing() {
        const phaseFromJHipster = super._writing();
        const myCustomPhaseSteps = {
                custom1() {
                    this.log(chalk.green("pre write"));
                },
                writing() {
                    this.log(chalk.green("to be override by jhipster phase"));
                },
                custom2() {
                    this.log(chalk.green("post write"));
                }
            }
        return Object.assign(myCustomPhaseSteps, phaseFromJHipster);
    }
```

##### **Reproduce the error**

Using the JHipster Blueprint Generator v0.0.3 try to create the blueprint module (e.g. spring-controller) and run it with the `jhipster spring-controller Foo` and at the end of the generation it will thrown the exception.

##### **JHipster Version(s)**

Which version of JHipster are you using, is it a regression? No it isn't, the version is 5.0.1

```
app-bm-1@0.0.0 D:\tests\jhipster\appBM1
`-- generator-jhipster@5.0.1  -> D:\tests\jhipster\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "appBM1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "blueprint": "generator-jhipster-b-helloworld"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) Client VM (build 25.162-b12, mixed mode)

git version 2.16.0.windows.2

node: v8.11.3

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.5.1

##### **Browsers and Operating System**
What OS are you on? Windows 10 Pro

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This has been fixed in master #7887 
Can you please try with master and let me know?
Make sure you are following the process 

During development of blueprint, please note the below steps. They are very important.

1. Link your blueprint globally 

Note: If you do not want to link the blueprint(step 3) to each project being created, use NPM instead of Yarn as yeoman doesn't seem to fetch globally linked Yarn modules. On the other hand, this means you have to use NPM in all the below steps as well.

```bash
cd <%= moduleName %>
npm link
```

2. Link a development version of JHipster to your blueprint (optional: required only if you want to use a non-released JHipster version, like the master branch or your own custom fork)

You could also use Yarn for this if you prefer

```bash
cd generator-jhipster
npm link

cd <%= moduleName %>
npm link generator-jhipster
```

3. Create a new folder for the app to be generated and link JHipster and your blueprint there

```bash
mkdir my-app && cd my-app

npm link generator-jhipster-<%= moduleName %>
npm link generator-jhipster (Optional: Needed only if you are using a non-released JHipster version)

jhipster -d --blueprint <%= moduleName %>

```

**Comment by pascalgrimaud** [comment]
@deepu105 :
I saw in the logs `D:\tests\b-helloworld\generators\spring-controller\templates\src\main\java\package\web\rest\Resource.java.ejs`

I compared:
- server: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/index.js#L453-L455
- spring-controller: https://github.com/jhipster/generator-jhipster/blob/master/generators/spring-controller/index.js#L106

I didn't apply the fix for spring-controller, I only worked on client and server, waiting your feedback before going further.

**Comment by pasqualevitale** [comment]
@deepu105, just to confirm the @pascalgrimaud response, also trying with the master "up to date" the problem still happen

**Comment by deepu105** [comment]
@pascalgrimaud oh sorry I didn't realize the fix wasn't on those subs. yes let's do the same as you did for others

**Comment by deepu105** [comment]
@pascalgrimaud should I do this or are you already on it?

**Comment by deepu105** [comment]
Also this means the same issue will be present in the spring-service sub as well, also in order to efficiently fix this we need to convert the writing phase to use metadata json similar to server/client

**Comment by pascalgrimaud** [comment]
Today, with @PierreBesson, we fixed the jhipster-registry which is currently broken :-( it was our priority

Then, I'd like to finish my CICD subgen before vacations, so I'm a little bit busy. 

If you can do it, yes, please. 
Otherwise, I'll do it after my PR for CICD

**Comment by pascalgrimaud** [comment]
to answer to you, I didn't start this yet, it's just on my todo list

**Comment by deepu105** [comment]
sure, if I manage to find time before you i'll make a comment to let you know that i'm starting

**Comment by pascalgrimaud** [comment]
ok, I will do the same

**Comment by pascalgrimaud** [comment]
@deepu105 : I'm starting this, right now
