### ISSUE TITLE
Default microservice stack doesnt work out of the box

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8301]
##### **Overview of the issue**

- [x] Unable to login to the registry
- [ ] Swagger API page doesn't work for microservices on Gateway #8328
- [ ] Swagger API page doesn't work for Gateway and microservices on Registry #8328
- [ ] The logs page on registry doesn't work for Gateway and microservices

<hr>

When I create a MS stack and use docker-compose to run it, there are some issues
1. Unable to login to the registry, it throws an error as below, I think this is after the JJWT upgrade
```
io.jsonwebtoken.security.WeakKeyException: The signing key's size is 376 bits which is not secure enough for the HS512 algorithm.  The JWT JWA Specification (RFC 7518, Section 3.2) states that keys used with HS512 MUST have a size >= 512 bits (the key size must be greater than or equal to the hash output size).  Consider using the io.jsonwebtoken.security.Keys class's 'secretKeyFor(SignatureAlgorithm.HS512)' method to create a key guaranteed to be secure enough for HS512.  See https://tools.ietf.org/html/rfc7518#section-3.2 for more information.

2. The microservices API are not fetched in Swagger, you get `Can't read from server. It may not have the appropriate access-control-origin settings.`

```
##### **Motivation for or Use Case**

Setup should work OOB

##### **Reproduce the error**
Do below steps or clone https://github.com/xebialabs/e-commerce-microservice and build images and run `docker-compose up`
1. create below app configs
2. Generate docker compose sub gen
3. do a `docker-compose up` and try to access mentioned apps/pages

##### **Related issues**

Probabaly related to #8145 

##### **JHipster Version(s)**

master

##### **JHipster configuration**

I havent removed the JWT keys, since its a demo app

#######  Gateway

```

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xebialabs.store",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "gateway",
    "baseName": "store",
    "packageName": "com.xebialabs.store",
    "packageFolder": "com/xebialabs/store",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl"
    ]
  }
}
```

###### MS 1

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xebialabs.notification",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "microservice",
    "baseName": "notification",
    "packageName": "com.xebialabs.notification",
    "packageFolder": "com/xebialabs/notification",
    "serverPort": "8082",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NTdlMTRhNzU4YTQ5MDQ0NDczMjJiZjVkM2UwNWI3N2VkZWNiMWI5YzlhZWQyYzlhZGI1Yzk3MDZkZDA2MGIwOWJjNmQxMTYwOWZkM2Y0MzgwYjc4YzIxOWFmNWU1NDBiOTUzMzZkNTNmYmNlMTkzY2RlNjA2Y2JjZWNlMzUwNTc=",
    "enableTranslation": true,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

###### MS 2

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xebialabs.invoice",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "microservice",
    "baseName": "invoice",
    "packageName": "com.xebialabs.invoice",
    "packageFolder": "com/xebialabs/invoice",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZTk4MjZjYjg5ODE0NTJlODFiNTlmOTJmZWNkNmY0MTFhYTQ3M2IxYzFkNTMyYmI3MTg0MWNlNDdkYjFlZTAwNzQ2NTBjZGJlZjkyMjYzODhjNWMxY2NiMDEwYTQ5MDM3Y2Y2NTAzOGRhZmFkNDYzZjcyMDIxZDA4ZDEyMzE0ZGQ=",
    "enableTranslation": true,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

######  Docker compose
```
{
  "generator-jhipster": {
    "appsFolders": [
      "invoice",
      "notification",
      "online-store"
    ],
    "directoryPath": "../",
    "gatewayType": "zuul",
    "clusteredDbApps": [],
    "monitoring": "elk",
    "consoleOptions": [],
    "serviceDiscoveryType": "eureka",
    "adminPassword": "admin",
    "jwtSecretKey": "YTI0ZDdiZDgzOGY3YzlhOGE3YmU4M2M0MDk4YTg1ODM5ZTYyMWQyMDI5MTA5NTcxMjc3MTMyZWExMjU1MWY3ZmYzMGVkNGYyY2E3ZGM5NTY4MWE3M2JmODExOTU2NDhiNGZmYg=="
  }
}
```

##### **Browsers and Operating System**

Chrome on Linux (Fedora 28)

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Also I get warnings when starting JHipster registry

```
jhipster-registry_1           | 
jhipster-registry_1           |         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
jhipster-registry_1           |         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
jhipster-registry_1           |         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
jhipster-registry_1           |   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
jhipster-registry_1           |   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
jhipster-registry_1           |    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
jhipster-registry_1           | 
jhipster-registry_1           | :: JHipster Registry :: Running Spring Boot 2.0.4.RELEASE ::
jhipster-registry_1           | :: http://www.jhipster.tech ::
jhipster-registry_1           | 
jhipster-registry_1           | 2018-09-12 12:15:33.614  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : The following profiles are active: dev,composite,swagger
jhipster-registry_1           | 2018-09-12 12:15:36.744  INFO 1 --- [           main] i.g.j.r.config.MetricsConfiguration      : Initializing Metrics Log reporting
jhipster-registry_1           | 2018-09-12 12:15:37.689  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
jhipster-registry_1           | 2018-09-12 12:15:39.310  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application configuration, using profiles: dev
jhipster-registry_1           | 2018-09-12 12:15:39.322  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application fully configured
jhipster-registry_1           | 2018-09-12 12:15:39.541 ERROR 1 --- [           main] i.g.j.r.security.jwt.TokenProvider       : WARNING! You are using the default JWT secret token, this **must** be changed in production!
jhipster-registry_1           | 2018-09-12 12:15:39.541  WARN 1 --- [           main] i.g.j.r.security.jwt.TokenProvider       : Warning: the JWT key used is not Base64-encoded. We recommend using the `jhipster.security.authentication.jwt.base64-secret` key for optimum security.
jhipster-registry_1           | 2018-09-12 12:15:41.791  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
jhipster-registry_1           | 2018-09-12 12:15:42.719 DEBUG 1 --- [           main] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Starting Swagger
jhipster-registry_1           | 2018-09-12 12:15:42.737 DEBUG 1 --- [           main] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Started Swagger in 17 ms
jhipster-registry_1           | 2018-09-12 12:15:44.703  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
jhipster-registry_1           | 2018-09-12 12:15:44.704  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Client configured to neither register nor query for data.
jhipster-registry_1           | 2018-09-12 12:15:44.717  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1536754544715 with initial instances count: 0
jhipster-registry_1           | 2018-09-12 12:15:45.036  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
jhipster-registry_1           | 2018-09-12 12:15:45.036  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
jhipster-registry_1           | 2018-09-12 12:15:45.036  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
jhipster-registry_1           | 2018-09-12 12:15:45.036  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
jhipster-registry_1           | 2018-09-12 12:15:46.303  INFO 1 --- [           main] i.g.j.r.config.LoggingConfiguration      : Initializing Logstash logging
jhipster-registry_1           | 2018-09-12 12:15:46.384  INFO 1 --- [           main] i.g.j.r.config.LoggingConfiguration      : Filtering metrics logs from all appenders except the LOGSTASH appender
jhipster-registry_1           | 2018-09-12 12:15:46.521  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
jhipster-registry_1           | 2018-09-12 12:15:46.521  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
jhipster-registry_1           | 2018-09-12 12:15:46.521  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
jhipster-registry_1           | 2018-09-12 12:15:46.521  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
jhipster-registry_1           | 2018-09-12 12:15:46.895  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : Started JHipsterRegistryApp in 15.828 seconds (JVM running for 16.558)
jhipster-registry_1           | 2018-09-12 12:15:46.904  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : 
jhipster-registry_1           | ----------------------------------------------------------
jhipster-registry_1           | 	Application 'jhipster-registry' is running! Access URLs:
jhipster-registry_1           | 	Local: 		http://localhost:8761
jhipster-registry_1           | 	External: 	http://192.168.32.2:8761
jhipster-registry_1           | 	Profile(s): 	[dev, composite, swagger]
jhipster-registry_1           | ----------------------------------------------------------
jhipster-registry_1           | 2018-09-12 12:15:46.905 ERROR 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : 
jhipster-registry_1           | ----------------------------------------------------------
jhipster-registry_1           | Your JWT secret key is not configured using Spring Cloud Config, you will not be able to 
jhipster-registry_1           | use the JHipster Registry dashboards to monitor external applications. 
jhipster-registry_1           | Please read the documentation at http://www.jhipster.tech/jhipster-registry/

```

**Comment by jsm174** [comment]
I'm having same identical issues.

I was able to get around your # 1, but putting an empty `secret` in `central-server-config/application.yml`

Then it will actually use the `base64-secret`. I posted this error at https://github.com/jhipster/jhipster-registry/issues/291

I'm struggling with your # 2.  If you update docker-compose.yml, add ports for the microservice,

```
        ports:
            - 8081:8081
```

and bring up the stack, you can definitely see the microservice is running.  

I'm not sure if its a CORS issue, because Chrome is returning ERR_CONTENT_DECODING_FAILED.

**Comment by jdubois** [comment]
I'm on it, but I can already tell you that the error message at the end of the JHipster Registry log is a bug, and is already fixed in master. You can safely ignore it.

Does it work without Docker Compose?

**Comment by deepu105** [comment]
I didn't try without docker compose yet

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
I can't reproduce for the moment, that's so weird :-(

**Comment by jdubois** [comment]
Oops sorry, I thought you couldn't log in the application!!!! I'm doing too much stuff at the same time! @deepu105 your issue is only logging in the JHipster Registry?

**Comment by jdubois** [comment]
OK, got it.... Sorry @deepu105 for the time lost. And also because that bug is probably my fault. It shouldn't be hard to solve, I'll update my findings here.

**Comment by DjayDev** [comment]
I think I have the same issue, but I don't have exactly the same messages.
Using jhipster @ 5.3.1, I've just generated a gateway and when I run it locally (with registry running in docker), I have this issue when I try to login:

`ERROR 16850 --- [  XNIO-2 task-3] c.m.myapp.aop.logging.LoggingAspect      : Exception in com.mycompany.myapp.web.rest.UserJWTController.authorize() with cause = 'NULL' and exception = 'The signing key's size is 312 bits which is not secure enough for the HS512 algorithm.  The JWT JWA Specification (RFC 7518, Section 3.2) states that keys used with HS512 MUST have a size >= 512 bits (the key size must be greater than or equal to the hash output size).  Consider using the io.jsonwebtoken.security.Keys class's 'secretKeyFor(SignatureAlgorithm.HS512)' method to create a key guaranteed to be secure enough for HS512.  See https://tools.ietf.org/html/rfc7518#section-3.2 for more information.'`

For information, my gateway:
`
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "gateway",
    "baseName": "gtway1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YTQ1NjgwOTE5NDQyZDM5ODc5YzZhMzgxMjUyNDI5Mzk5MTUxMjcwOWQ4NGE1OGVlZTQzOWJkMmMzOTJmZmEwYmVlOTBmZGY4MGY1MzE2MjRhMzFiNThlNzZiYTMxNzEwMDhlNWQ1OTA0YmM1ZjU3NDlkOWIwZjM2NmM5ODVjMTI=",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
`

If you think it's a different issue, let me know and I'll create a new one.

**Comment by DjayDev** [comment]
To workaround the issue, I changed 
https://github.com/jhipster/generator-jhipster/blob/03466457e3f26ea3cefa6791a59e45b38f7bdbdb/generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs#L97
from HS512 to HS256

but it's definitely not a solution.

**Comment by jdubois** [comment]
@DjayDev I'm guessing your issue is just that your key is too short. The newest version of JJWT forces you to have a bigger key, which is good, but you need to update the key in your config.

**Comment by DjayDev** [comment]
@jdubois I agree, but I haven't touch anything from the generated app. It was like that out of the box. So maybe should I fill a new issue?

**Comment by jdubois** [comment]
Oh, in that case I'm not sure this isn't the same issue... so no, let's keep it like this

**Comment by jmillard-optimo** [comment]
@DjayDev: I think this is related to https://github.com/jhipster/jhipster-registry/issues/291

Did you try putting an empty secret line in central-server-config/application.yml, like above
 https://github.com/jhipster/generator-jhipster/issues/8301#issuecomment-420648603 

```
jhipster:
    security:
        authentication:
            jwt:
                secret:
                base64-secret: YTg3OTc5MTJhOWY0ZTI2YTcwYTA1NzExZjk1MWIzOGMzNGQyYTZlNTNiYzU5YTEyZWMzNjU1ZjczYmUzYzAzZDM4YjYwODM1YWExNDllY2ZlZDllMzFlYmViOTRiOWMzM2MwOQ==
```

@jdubois, I've created a video, walking through a simple gateway, and a simple microservice, showing  
@deepu105 issue # 2:

https://www.youtube.com/watch?v=gE9pMEhEQVg

**Comment by jsm174** [comment]
@DjayDev: I think this is related to https://github.com/jhipster/jhipster-registry/issues/291

Did you try putting an empty secret line in central-server-config/application.yml, like above
 https://github.com/jhipster/generator-jhipster/issues/8301#issuecomment-420648603 

```
jhipster:
    security:
        authentication:
            jwt:
                secret:
                base64-secret: YTg3OTc5MTJhOWY0ZTI2YTcwYTA1NzExZjk1MWIzOGMzNGQyYTZlNTNiYzU5YTEyZWMzNjU1ZjczYmUzYzAzZDM4YjYwODM1YWExNDllY2ZlZDllMzFlYmViOTRiOWMzM2MwOQ==
```

@jdubois, I've created a video, walking through a simple gateway, and a simple microservice, showing  
@deepu105 issue # 2:

https://www.youtube.com/watch?v=gE9pMEhEQVg

**Comment by DjayDev** [comment]
@jsm174 I've tested also with the empty secret but still the same issue

**Comment by jdubois** [comment]
I have a fix that should be available soon - will some of you be available for testing tonight? The issue is that the `develop` branch is currently broken, so I need to push on `master`, and of course this is bad

**Comment by DjayDev** [comment]
@jdubois I can do some tests tonight

**Comment by jsm174** [comment]
@jdubois Same here!

**Comment by jdubois** [comment]
Awesome :-)
So I just pushed to master, you need to wait until the new "master" build is available at https://hub.docker.com/r/jhipster/jhipster-registry/builds/

And then in your `jhipster-registry.yml`, next to your `docker-compose.yml`, you need to write `image: jhipster/jhipster-registry:master`.

If you want to use a Base64 secret key, you probably will need to set up also an empty secret key. Otherwise it'll take the default secret key, which is not good for production.

**Comment by jsm174** [comment]
@jdubois , just tried out master as it finished building. 

```
jhipster-registry_1         |
jhipster-registry_1         |         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
jhipster-registry_1         |         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
jhipster-registry_1         |         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
jhipster-registry_1         |   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
jhipster-registry_1         |   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
jhipster-registry_1         |    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
jhipster-registry_1         |
jhipster-registry_1         | :: JHipster Registry :: Running Spring Boot 2.0.4.RELEASE ::
jhipster-registry_1         | :: https://www.jhipster.tech ::
jhipster-registry_1         |
jhipster-registry_1         | 2018-09-12 17:26:33.741  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : The following profiles are active: dev,composite,swagger
jhipster-registry_1         | 2018-09-12 17:26:38.451  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
jhipster-registry_1         | 2018-09-12 17:26:40.375  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application configuration, using profiles: dev
jhipster-registry_1         | 2018-09-12 17:26:40.387  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application fully configured
jhipster-registry_1         | 2018-09-12 17:26:43.461  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
jhipster-registry_1         | 2018-09-12 17:26:44.677 DEBUG 1 --- [           main] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Starting Swagger
jhipster-registry_1         | 2018-09-12 17:26:44.704 DEBUG 1 --- [           main] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Started Swagger in 27 ms
jhipster-registry_1         | 2018-09-12 17:26:46.539  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
jhipster-registry_1         | 2018-09-12 17:26:46.539  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Client configured to neither register nor query for data.
jhipster-registry_1         | 2018-09-12 17:26:46.554  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1536773206551 with initial instances count: 0
jhipster-registry_1         | 2018-09-12 17:26:46.936  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
jhipster-registry_1         | 2018-09-12 17:26:46.937  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
jhipster-registry_1         | 2018-09-12 17:26:46.937  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
jhipster-registry_1         | 2018-09-12 17:26:46.937  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
jhipster-registry_1         | 2018-09-12 17:26:48.738  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
jhipster-registry_1         | 2018-09-12 17:26:48.739  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
jhipster-registry_1         | 2018-09-12 17:26:48.740  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
jhipster-registry_1         | 2018-09-12 17:26:48.740  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
jhipster-registry_1         | 2018-09-12 17:26:49.295  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : Started JHipsterRegistryApp in 19.255 seconds (JVM running for 20.626)
jhipster-registry_1         | 2018-09-12 17:26:49.303  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       :
jhipster-registry_1         | ----------------------------------------------------------
jhipster-registry_1         | 	Application 'jhipster-registry' is running! Access URLs:
jhipster-registry_1         | 	Local: 		http://localhost:8761
jhipster-registry_1         | 	External: 	http://192.168.32.6:8761
jhipster-registry_1         | 	Profile(s): 	[dev, composite, swagger]
jhipster-registry_1         | ----------------------------------------------------------
jhipster-registry_1         | 2018-09-12 17:26:49.304 ERROR 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       :
jhipster-registry_1         | ----------------------------------------------------------
jhipster-registry_1         | Your JWT secret key is not configured using Spring Cloud Config, you will not be able to
jhipster-registry_1         | use the JHipster Registry dashboards to monitor external applications.
jhipster-registry_1         | Please read the documentation at https://www.jhipster.tech/jhipster-registry/
jhipster-registry_1         | ----------------------------------------------------------
```

Got through the base64 message, but now I'm seeing a new message at the end.

Also, still can't access microservice.

**Comment by jdubois** [comment]
Thanks! And in your "central-config", I guess you have a base64 secret? Can you also put an empty secret?
I need to check what we generate here

**Comment by jsm174** [comment]
Yes. Updated my comment above to clarify.

**Comment by DjayDev** [comment]
I've tested also with different `application.yml` configs:
- having only secret (legacy): fail
- keeping secret and adding base64-secret: OK
- empty secret with base64-secret: OK
- no secret, only base64-secret: fail : same error as @jsm174 (JWT secret key not configured)

I'll retest the gateway as I thing it's the same issue.

**Comment by jdubois** [comment]
Thanks a lot for the tests! There's definitely something I don't get on that code.

**Comment by DjayDev** [comment]
I've tested again the gateway with Jhipster@5.3.1 and I could not reproduce the issue I had before...

**Comment by jdubois** [comment]
OK, I've just pushed a far more "aggressive" approach, with no default token. That forces the user to configure one, but he needs to do it anyway.

I know it's very late (at least in France!), if anybody has the time to test the new "master" image (like my comment above), any help is really welcome.

**Comment by jdubois** [comment]
Great news, I just tested and this looks good :-)
@DjayDev @jsm174 @deepu105 can you have a look? Just use the latest "master" image on Docker Hub.

**Comment by DjayDev** [comment]
I tested the master uploaded  a few minutes ago:
- only a secret: fail: the registry won't start (expected)
- only base64: OK
so I confirm it looks better.

**Comment by DjayDev** [comment]
Here are my latest test results:
- if I put `secret: top-secret` in the application.yml file, it fails
- if I put `secret: ZDgxY2UwZDk0MDU1ZTMwODIwMDVhMjllNmVjM2ZlNTA2ZmI0NDUzZThjMTY5ZTY1YTc4ZjQyOTg4ZDJkOTcxNTg2NTUwMWU2NmQwYmM2OWI3YjIxNjc3YjBkOWVkZDQ2ZDdmZGM0NmU4YzcyNWFiMTdlZDRkZGNkMmVkMzI1Njc=`, it works, with the warning: 

```INFO 1 --- [           main] i.g.j.r.security.jwt.TokenProvider       : The JWT key used is not Base64-encoded. We recommend using the `jhipster.security.authentication.jwt.base64-secret` key for optimum security.```

**Comment by jdubois** [comment]
OK, 2 things here:

- For the JWT key, this looks all OK from what I read here. @deepu105 can you also test? That would made me totally sure it's good. I will also lower the warning level: everybody is worried about this, when it's not that bad to have the non-base64 secret key.
- For CORS, I'll have a look, but it's another problem so I didn't work on it yet

**Comment by jsm174** [comment]
> * For CORS, I'll have a look, but it's another problem so I didn't work on it yet

I have tried several different releases of JHipster. This broke between 5.1.0 and 5.2.0.

**Comment by jsm174** [comment]
I narrowed it down some more.

The latest commit where microservices using docker-compose worked for me: 

`fix tests` - https://github.com/jhipster/generator-jhipster/commit/4327015c5ce355c1b3f2ed8415be0d6610e138e9

They started failing on:

`Upgrade to JHipster dependencies 2.0.15` - https://github.com/jhipster/generator-jhipster/commit/10dd1ac5eac6c373cb476223bc62381cf601ab20

Just to show how I test, I put together a script:

```
docker volume prune
yarn global remove generator-jhipster
#cd generator-jhipster-b8c173430ca11cbcb29665523e312e1c7daf049d - AUG 9 - Microservice via swagger works
#cd generator-jhipster-6ca62a64a3320a5490536377eb34fe88829f44b4 - AUG 9 - Gateway fails compiling build because of JDL
#cd generator-jhipster-c9ee896951ee73a59dde58cb854e00a258967d89 - AUG 9 - Gateway fails compiling build because of JDL
#cd generator-jhipster-f560230e58265dde55948c9fa78d3c5f1a5a0bcb - AUG 9 - Gateway fails compiling build because of JDL
#cd generator-jhipster-2d77e54e091a88abef28741cf7975465dcbd780c - AUG 13 - Gateway Fails compiling build because of JDL
#cd generator-jhipster-c575c6073c5c2ec54870d24636123ad64c525165 - AUG 13 - Microservice via swagger does not work
#cd generator-jhipster-6ca62a64a3320a5490536377eb34fe88829f44b4 - AUG 9 - Works with no JDL in gateway
#cd generator-jhipster-4327015c5ce355c1b3f2ed8415be0d6610e138e9 - Works with no JDL in gateway
#cd generator-jhipster-2d77e54e091a88abef28741cf7975465dcbd780c - Does not work even with no JDL in gateway
cd generator-jhipster-10dd1ac5eac6c373cb476223bc62381cf601ab20
npm install
yarn install
yarn global add file:$(pwd)
cd ..
rm -rf jhtest
mkdir jhtest
cd jhtest
mkdir gateway
mkdir microservice1
cp ~/Desktop/microservice1.jh gateway
cp ~/Desktop/microservice1.jh microservice1
cd gateway
jhipster
./gradlew -Pprod bootWar buildDocker
cd ..
cd microservice1
jhipster
jhipster import-jdl microservice1.jh
./gradlew -Pprod bootWar buildDocker
cd ..
jhipster docker-compose
docker-compose up

**Comment by deepu105** [comment]
Sure I'll test this tomorrow. I should be using the master branch image of
registry right?

**Comment by jdubois** [comment]
Yes, the 'develop' looks broken.

**Comment by pascalgrimaud** [comment]
@jsm174 : thanks a lot for your analyze, so I tried to do the same, so here a little resume:

- using jhipster-registry master, I don't have any issue with JWT -> so for me, this point is resolved!

- the CORS problem comes from the Upgrade to JHipster dependencies 2.0.15 -> it includes this commit https://github.com/jhipster/jhipster/commit/a3b3f30b22faa37571fce0dcc16524feff3eafa7 with Finchley.RELEASE -> Finchley.SR1
- there was a 1st fix https://github.com/jhipster/generator-jhipster/pull/8100 but it seems not enough
- probably related to this ticket: https://github.com/spring-cloud/spring-cloud-netflix/issues/3126
- I don't find another properties to play with: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/ZuulProperties.java#L143-L151

**Comment by deepu105** [comment]
Also please note that the swagger API issue I mentioned is now present in both Registry and Gateway (with 5.2 it was working atleast in the registry)

**Comment by deepu105** [comment]
Also noticed another issue http://localhost:8761/#/logs doesnt seem to work for microservices

**Comment by jdubois** [comment]
OK that's awesome that the JWT issue is fixed, I'll do a release this afternoon (also a generator-jhipster release, so you get the correct Docker image).
For CORS and logs I'll have a look, and hopefully we can fix this before this afternoon, but that's less urgent.

**Comment by jdubois** [comment]
I just had no time to do anything else (as we had the master build failing), so I guess I'll do a release with just the JWT part corrected.
The rest will need to be done later.

**Comment by deepu105** [comment]
closing as remaining issues are moved to new ones with bounty
